on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: node -v
      - run: npm -v
      - run: yarn
      - run: yarn test
      - run: npx github:helloitsjoe/release-toolkit publish --no-npm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
