on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: npx helloitsjoe/release-toolkit publish
      - run: |
          curl --request POST \
            --header "Accept: application/vnd.github.v3+json" \
            --header "authorization: token ${{ secrets.GITHUB_TOKEN }} \
            --url https://api.github.com/repos/${{ github.repository }}/release
            --data '{"tag_name": "v1", "name": "v1"}'
            --fail
        env:
          GIT_RELEASE_TOKEN: ${{ secrets.GIT_RELEASE_TOKEN }}
